language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
before_script:
  - psql -c "CREATE USER taskmanager WITH PASSWORD 'qazwsx';" -U postgres
  - psql -c 'create database "my_database_test" owner "taskmanager";' -U postgres
script: "bundle exec rake test"
